// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMmXGuAUK2rxz9KTMZbCV9ERHtJnwELnU',
    appId: '1:791119424451:web:651aecd73c924cf49aeb76',
    messagingSenderId: '791119424451',
    projectId: 'sevycotroller',
    authDomain: 'sevycotroller.firebaseapp.com',
    storageBucket: 'sevycotroller.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApGk2dJmJFXtW8PizFRRl6O8RWd-4Y-FE',
    appId: '1:791119424451:android:9fa222b2ca6724e49aeb76',
    messagingSenderId: '791119424451',
    projectId: 'sevycotroller',
    storageBucket: 'sevycotroller.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChEI51EItejsUpyIDLD_a5gmAFUp-_yaM',
    appId: '1:791119424451:ios:7e2f074ceb91a95d9aeb76',
    messagingSenderId: '791119424451',
    projectId: 'sevycotroller',
    storageBucket: 'sevycotroller.appspot.com',
    iosClientId: '791119424451-lbqp866se57hki2japd2pjnmseisrsnf.apps.googleusercontent.com',
    iosBundleId: 'com.sevy.controller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChEI51EItejsUpyIDLD_a5gmAFUp-_yaM',
    appId: '1:791119424451:ios:7e2f074ceb91a95d9aeb76',
    messagingSenderId: '791119424451',
    projectId: 'sevycotroller',
    storageBucket: 'sevycotroller.appspot.com',
    iosClientId: '791119424451-lbqp866se57hki2japd2pjnmseisrsnf.apps.googleusercontent.com',
    iosBundleId: 'com.sevy.controller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMmXGuAUK2rxz9KTMZbCV9ERHtJnwELnU',
    appId: '1:791119424451:web:ef10e1964f318cc49aeb76',
    messagingSenderId: '791119424451',
    projectId: 'sevycotroller',
    authDomain: 'sevycotroller.firebaseapp.com',
    storageBucket: 'sevycotroller.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBMmXGuAUK2rxz9KTMZbCV9ERHtJnwELnU',
    appId: '1:791119424451:web:e5a077933a283cbb9aeb76',
    messagingSenderId: '791119424451',
    projectId: 'sevycotroller',
    authDomain: 'sevycotroller.firebaseapp.com',
    storageBucket: 'sevycotroller.appspot.com',
  );
}
